"""
Card data for the Splendor game.
This module contains all the game cards and nobles data.
"""

# Level 1 Development Cards (lowest cost, lowest points)
level1_cards = [
    {
        'id': 'L1_1',
        'gem_color': 'black',  # The color of bonus this card provides
        'points': 0,
        'cost': {'white': 1, 'blue': 1, 'green': 1, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_2',
        'gem_color': 'black',
        'points': 0,
        'cost': {'white': 1, 'blue': 2, 'green': 1, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_3',
        'gem_color': 'black',
        'points': 0,
        'cost': {'white': 2, 'blue': 2, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_4',
        'gem_color': 'black',
        'points': 1,
        'cost': {'blue': 4},
        'level': 1,
    },
    {
        'id': 'L1_5',
        'gem_color': 'black',
        'points': 0,
        'cost': {'green': 3},
        'level': 1,
    },
    {
        'id': 'L1_6',
        'gem_color': 'black',
        'points': 0,
        'cost': {'green': 2, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_7',
        'gem_color': 'black',
        'points': 0,
        'cost': {'white': 2, 'green': 2},
        'level': 1,
    },
    {
        'id': 'L1_8',
        'gem_color': 'black',
        'points': 0,
        'cost': {'white': 3},
        'level': 1,
    },
    # Blue gem cards
    {
        'id': 'L1_9',
        'gem_color': 'blue',
        'points': 0,
        'cost': {'black': 1, 'white': 1, 'green': 1, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_10',
        'gem_color': 'blue',
        'points': 0,
        'cost': {'black': 1, 'white': 2, 'green': 1, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_11',
        'gem_color': 'blue',
        'points': 0,
        'cost': {'black': 2, 'white': 2, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_12',
        'gem_color': 'blue',
        'points': 1,
        'cost': {'green': 4},
        'level': 1,
    },
    {
        'id': 'L1_13',
        'gem_color': 'blue',
        'points': 0,
        'cost': {'red': 3},
        'level': 1,
    },
    {
        'id': 'L1_14',
        'gem_color': 'blue',
        'points': 0,
        'cost': {'red': 2, 'black': 1},
        'level': 1,
    },
    {
        'id': 'L1_15',
        'gem_color': 'blue',
        'points': 0,
        'cost': {'black': 2, 'red': 2},
        'level': 1,
    },
    {
        'id': 'L1_16',
        'gem_color': 'blue',
        'points': 0,
        'cost': {'black': 3},
        'level': 1,
    },
    # Green gem cards
    {
        'id': 'L1_17',
        'gem_color': 'green',
        'points': 0,
        'cost': {'black': 1, 'white': 1, 'blue': 1, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_18',
        'gem_color': 'green',
        'points': 0,
        'cost': {'black': 1, 'white': 1, 'blue': 1, 'red': 2},
        'level': 1,
    },
    {
        'id': 'L1_19',
        'gem_color': 'green',
        'points': 0,
        'cost': {'black': 1, 'white': 2, 'blue': 2},
        'level': 1,
    },
    {
        'id': 'L1_20',
        'gem_color': 'green',
        'points': 1,
        'cost': {'red': 4},
        'level': 1,
    },
    {
        'id': 'L1_21',
        'gem_color': 'green',
        'points': 0,
        'cost': {'white': 3},
        'level': 1,
    },
    {
        'id': 'L1_22',
        'gem_color': 'green',
        'points': 0,
        'cost': {'white': 2, 'black': 1},
        'level': 1,
    },
    {
        'id': 'L1_23',
        'gem_color': 'green',
        'points': 0,
        'cost': {'black': 2, 'white': 2},
        'level': 1,
    },
    {
        'id': 'L1_24',
        'gem_color': 'green',
        'points': 0,
        'cost': {'blue': 3},
        'level': 1,
    },
    # Red gem cards
    {
        'id': 'L1_25',
        'gem_color': 'red',
        'points': 0,
        'cost': {'black': 1, 'white': 1, 'blue': 1, 'green': 1},
        'level': 1,
    },
    {
        'id': 'L1_26',
        'gem_color': 'red',
        'points': 0,
        'cost': {'black': 2, 'white': 1, 'blue': 1, 'green': 1},
        'level': 1,
    },
    {
        'id': 'L1_27',
        'gem_color': 'red',
        'points': 0,
        'cost': {'white': 1, 'blue': 2, 'green': 2},
        'level': 1,
    },
    {
        'id': 'L1_28',
        'gem_color': 'red',
        'points': 1,
        'cost': {'black': 4},
        'level': 1,
    },
    {
        'id': 'L1_29',
        'gem_color': 'red',
        'points': 0,
        'cost': {'blue': 3},
        'level': 1,
    },
    {
        'id': 'L1_30',
        'gem_color': 'red',
        'points': 0,
        'cost': {'blue': 2, 'green': 1},
        'level': 1,
    },
    {
        'id': 'L1_31',
        'gem_color': 'red',
        'points': 0,
        'cost': {'green': 2, 'blue': 2},
        'level': 1,
    },
    {
        'id': 'L1_32',
        'gem_color': 'red',
        'points': 0,
        'cost': {'green': 3},
        'level': 1,
    },
    # White gem cards
    {
        'id': 'L1_33',
        'gem_color': 'white',
        'points': 0,
        'cost': {'black': 1, 'blue': 1, 'green': 1, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_34',
        'gem_color': 'white',
        'points': 0,
        'cost': {'black': 1, 'blue': 1, 'green': 2, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_35',
        'gem_color': 'white',
        'points': 0,
        'cost': {'black': 1, 'blue': 1, 'green': 2, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_36',
        'gem_color': 'white',
        'points': 1,
        'cost': {'white': 4},
        'level': 1,
    },
    {
        'id': 'L1_37',
        'gem_color': 'white',
        'points': 0,
        'cost': {'black': 3},
        'level': 1,
    },
    {
        'id': 'L1_38',
        'gem_color': 'white',
        'points': 0,
        'cost': {'black': 2, 'red': 1},
        'level': 1,
    },
    {
        'id': 'L1_39',
        'gem_color': 'white',
        'points': 0,
        'cost': {'red': 2, 'black': 2},
        'level': 1,
    },
    {
        'id': 'L1_40',
        'gem_color': 'white',
        'points': 0,
        'cost': {'red': 3},
        'level': 1,
    },
]

# Level 2 Development Cards (medium cost, medium points)
level2_cards = [
    # Black gem cards
    {
        'id': 'L2_1',
        'gem_color': 'black',
        'points': 1,
        'cost': {'white': 3, 'blue': 2, 'green': 2},
        'level': 2,
    },
    {
        'id': 'L2_2',
        'gem_color': 'black',
        'points': 1,
        'cost': {'white': 3, 'green': 3, 'red': 0},
        'level': 2,
    },
    {
        'id': 'L2_3',
        'gem_color': 'black',
        'points': 2,
        'cost': {'red': 5},
        'level': 2,
    },
    {
        'id': 'L2_4',
        'gem_color': 'black',
        'points': 2,
        'cost': {'green': 4, 'red': 1},
        'level': 2,
    },
    {
        'id': 'L2_5',
        'gem_color': 'black',
        'points': 2,
        'cost': {'white': 5},
        'level': 2,
    },
    {
        'id': 'L2_6',
        'gem_color': 'black',
        'points': 3,
        'cost': {'black': 6},
        'level': 2,
    },
    # Blue gem cards
    {
        'id': 'L2_7',
        'gem_color': 'blue',
        'points': 1,
        'cost': {'black': 3, 'white': 2, 'red': 2},
        'level': 2,
    },
    {
        'id': 'L2_8',
        'gem_color': 'blue',
        'points': 1,
        'cost': {'black': 3, 'red': 3},
        'level': 2,
    },
    {
        'id': 'L2_9',
        'gem_color': 'blue',
        'points': 2,
        'cost': {'white': 5},
        'level': 2,
    },
    {
        'id': 'L2_10',
        'gem_color': 'blue',
        'points': 2,
        'cost': {'red': 4, 'black': 1},
        'level': 2,
    },
    {
        'id': 'L2_11',
        'gem_color': 'blue',
        'points': 2,
        'cost': {'black': 5},
        'level': 2,
    },
    {
        'id': 'L2_12',
        'gem_color': 'blue',
        'points': 3,
        'cost': {'blue': 6},
        'level': 2,
    },
    # Green gem cards
    {
        'id': 'L2_13',
        'gem_color': 'green',
        'points': 1,
        'cost': {'black': 2, 'white': 3, 'blue': 2},
        'level': 2,
    },
    {
        'id': 'L2_14',
        'gem_color': 'green',
        'points': 1,
        'cost': {'black': 3, 'blue': 3},
        'level': 2,
    },
    {
        'id': 'L2_15',
        'gem_color': 'green',
        'points': 2,
        'cost': {'black': 5},
        'level': 2,
    },
    {
        'id': 'L2_16',
        'gem_color': 'green',
        'points': 2,
        'cost': {'white': 4, 'blue': 1},
        'level': 2,
    },
    {
        'id': 'L2_17',
        'gem_color': 'green',
        'points': 2,
        'cost': {'blue': 5},
        'level': 2,
    },
    {
        'id': 'L2_18',
        'gem_color': 'green',
        'points': 3,
        'cost': {'green': 6},
        'level': 2,
    },
    # Red gem cards
    {
        'id': 'L2_19',
        'gem_color': 'red',
        'points': 1,
        'cost': {'black': 2, 'white': 2, 'green': 3},
        'level': 2,
    },
    {
        'id': 'L2_20',
        'gem_color': 'red',
        'points': 1,
        'cost': {'white': 3, 'green': 3},
        'level': 2,
    },
    {
        'id': 'L2_21',
        'gem_color': 'red',
        'points': 2,
        'cost': {'blue': 5},
        'level': 2,
    },
    {
        'id': 'L2_22',
        'gem_color': 'red',
        'points': 2,
        'cost': {'black': 4, 'white': 1},
        'level': 2,
    },
    {
        'id': 'L2_23',
        'gem_color': 'red',
        'points': 2,
        'cost': {'green': 5},
        'level': 2,
    },
    {
        'id': 'L2_24',
        'gem_color': 'red',
        'points': 3,
        'cost': {'red': 6},
        'level': 2,
    },
    # White gem cards
    {
        'id': 'L2_25',
        'gem_color': 'white',
        'points': 1,
        'cost': {'blue': 3, 'green': 2, 'red': 2},
        'level': 2,
    },
    {
        'id': 'L2_26',
        'gem_color': 'white',
        'points': 1,
        'cost': {'blue': 3, 'green': 3},
        'level': 2,
    },
    {
        'id': 'L2_27',
        'gem_color': 'white',
        'points': 2,
        'cost': {'green': 5},
        'level': 2,
    },
    {
        'id': 'L2_28',
        'gem_color': 'white',
        'points': 2,
        'cost': {'blue': 4, 'green': 1},
        'level': 2,
    },
    {
        'id': 'L2_29',
        'gem_color': 'white',
        'points': 2,
        'cost': {'red': 5},
        'level': 2,
    },
    {
        'id': 'L2_30',
        'gem_color': 'white',
        'points': 3,
        'cost': {'white': 6},
        'level': 2,
    },
]

# Level 3 Development Cards (highest cost, highest points)
level3_cards = [
    # Black gem cards
    {
        'id': 'L3_1',
        'gem_color': 'black',
        'points': 3,
        'cost': {'white': 3, 'blue': 3, 'green': 5, 'red': 3},
        'level': 3,
    },
    {
        'id': 'L3_2',
        'gem_color': 'black',
        'points': 4,
        'cost': {'red': 7},
        'level': 3,
    },
    {
        'id': 'L3_3',
        'gem_color': 'black',
        'points': 4,
        'cost': {'green': 3, 'red': 6, 'black': 3},
        'level': 3,
    },
    {
        'id': 'L3_4',
        'gem_color': 'black',
        'points': 5,
        'cost': {'red': 7, 'black': 3},
        'level': 3,
    },
    # Blue gem cards
    {
        'id': 'L3_5',
        'gem_color': 'blue',
        'points': 3,
        'cost': {'black': 3, 'white': 5, 'green': 3, 'red': 3},
        'level': 3,
    },
    {
        'id': 'L3_6',
        'gem_color': 'blue',
        'points': 4,
        'cost': {'white': 7},
        'level': 3,
    },
    {
        'id': 'L3_7',
        'gem_color': 'blue',
        'points': 4,
        'cost': {'black': 6, 'white': 3, 'blue': 3},
        'level': 3,
    },
    {
        'id': 'L3_8',
        'gem_color': 'blue',
        'points': 5,
        'cost': {'white': 7, 'blue': 3},
        'level': 3,
    },
    # Green gem cards
    {
        'id': 'L3_9',
        'gem_color': 'green',
        'points': 3,
        'cost': {'black': 5, 'white': 3, 'blue': 3, 'red': 3},
        'level': 3,
    },
    {
        'id': 'L3_10',
        'gem_color': 'green',
        'points': 4,
        'cost': {'black': 7},
        'level': 3,
    },
    {
        'id': 'L3_11',
        'gem_color': 'green',
        'points': 4,
        'cost': {'white': 6, 'blue': 3, 'green': 3},
        'level': 3,
    },
    {
        'id': 'L3_12',
        'gem_color': 'green',
        'points': 5,
        'cost': {'black': 7, 'green': 3},
        'level': 3,
    },
    # Red gem cards
    {
        'id': 'L3_13',
        'gem_color': 'red',
        'points': 3,
        'cost': {'black': 3, 'white': 3, 'blue': 3, 'green': 5},
        'level': 3,
    },
    {
        'id': 'L3_14',
        'gem_color': 'red',
        'points': 4,
        'cost': {'green': 7},
        'level': 3,
    },
    {
        'id': 'L3_15',
        'gem_color': 'red',
        'points': 4,
        'cost': {'black': 3, 'blue': 6, 'red': 3},
        'level': 3,
    },
    {
        'id': 'L3_16',
        'gem_color': 'red',
        'points': 5,
        'cost': {'green': 7, 'red': 3},
        'level': 3,
    },
    # White gem cards
    {
        'id': 'L3_17',
        'gem_color': 'white',
        'points': 3,
        'cost': {'black': 3, 'blue': 5, 'green': 3, 'red': 3},
        'level': 3,
    },
    {
        'id': 'L3_18',
        'gem_color': 'white',
        'points': 4,
        'cost': {'blue': 7},
        'level': 3,
    },
    {
        'id': 'L3_19',
        'gem_color': 'white',
        'points': 4,
        'cost': {'green': 6, 'red': 3, 'white': 3},
        'level': 3,
    },
    {
        'id': 'L3_20',
        'gem_color': 'white',
        'points': 5,
        'cost': {'blue': 7, 'white': 3},
        'level': 3,
    },
]

# Noble Tiles - Each noble requires a specific combination of gem bonuses
noble_tiles = [
    {
        'id': 'noble_1',
        'name': 'Catherine de Medici',
        'points': 3,
        'requirements': {'black': 3, 'red': 3, 'white': 3},
    },
    {
        'id': 'noble_2',
        'name': 'Francis I of France',
        'points': 3,
        'requirements': {'blue': 3, 'green': 3, 'red': 3},
    },
    {
        'id': 'noble_3',
        'name': 'Henry VIII',
        'points': 3,
        'requirements': {'blue': 4, 'red': 4},
    },
    {
        'id': 'noble_4',
        'name': 'Isabella of Castile',
        'points': 3,
        'requirements': {'black': 4, 'white': 4},
    },
    {
        'id': 'noble_5',
        'name': 'Suleiman the Magnificent',
        'points': 3,
        'requirements': {'green': 4, 'red': 4},
    },
    {
        'id': 'noble_6',
        'name': 'Eleanor of Aquitaine',
        'points': 3,
        'requirements': {'black': 3, 'green': 3, 'white': 3},
    },
    {
        'id': 'noble_7',
        'name': 'Charles V',
        'points': 3,
        'requirements': {'black': 3, 'blue': 3, 'green': 3},
    },
    {
        'id': 'noble_8',
        'name': 'Anne of Brittany',
        'points': 3,
        'requirements': {'blue': 4, 'green': 4},
    },
    {
        'id': 'noble_9',
        'name': 'Niccolo Machiavelli',
        'points': 3,
        'requirements': {'black': 4, 'green': 4},
    },
    {
        'id': 'noble_10',
        'name': 'Elizabeth I',
        'points': 3,
        'requirements': {'black': 4, 'blue': 4},
    },
]