"""board games table

Revision ID: 5f60d471d05e
Revises: 15c61a76fd94
Create Date: 2025-03-26 15:38:37.035288
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f60d471d05e'
down_revision = '15c61a76fd94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to the next version.

    This method should contain all the changes to be applied when migrating
    to a newer version of the database schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert database schema to the previous version.

    This method should contain the necessary steps to undo the changes
    made in the upgrade() method, ensuring database schema can be rolled back.
    """
    pass
