"""init

Revision ID: a47dd8a087d0
Revises: 
Create Date: 2025-03-25 20:35:35.126397
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47dd8a087d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to the next version.

    This method should contain all the changes to be applied when migrating
    to a newer version of the database schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert database schema to the previous version.

    This method should contain the necessary steps to undo the changes
    made in the upgrade() method, ensuring database schema can be rolled back.
    """
    pass
