"""add rooms players statuses

Revision ID: c2f37e46fccf
Revises: e44c7f6bb137
Create Date: 2025-03-27 13:37:21.769987
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f37e46fccf'
down_revision = 'e44c7f6bb137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to the next version.

    This method should contain all the changes to be applied when migrating
    to a newer version of the database schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_room_players', sa.Column('status', sa.Enum('READY', 'NOT_READY', 'IN_GAME', name='playerstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert database schema to the previous version.

    This method should contain the necessary steps to undo the changes
    made in the upgrade() method, ensuring database schema can be rolled back.
    """
    pass
