"""add rooms players and status

Revision ID: e44c7f6bb137
Revises: 8c4001df6895
Create Date: 2025-03-27 11:11:10.850088
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44c7f6bb137'
down_revision = '8c4001df6895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade database schema to the next version.

    This method should contain all the changes to be applied when migrating
    to a newer version of the database schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('max_players', sa.Integer(), nullable=False))
    op.add_column('game_rooms', sa.Column('status', sa.Enum('WAITING', 'STARTED', 'ENDED', name='roomstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert database schema to the previous version.

    This method should contain the necessary steps to undo the changes
    made in the upgrade() method, ensuring database schema can be rolled back.
    """
    pass
